gOtherText_NewName::
	.string "NEW NAME$"

gNameChoice_Green::
	.string "GREEN$"

gNameChoice_Red::
	.string "RED$"

gNameChoice_Leaf::
	.string "LEAF$"

gNameChoice_Fire::
	.string "FIRE$"

gNameChoice_Gary::
	.string "GARY$"

gNameChoice_Kaz::
	.string "KAZ$"

gNameChoice_Toru::
	.string "TORU$"

gNameChoice_Ash::
	.string "ASH$"

gNameChoice_Kene::
	.string "KENE$"

gNameChoice_Geki::
	.string "GEKI$"

gNameChoice_Jak::
	.string "JAK$"

gNameChoice_Janne::
	.string "JANNE$"

gNameChoice_Jonn::
	.string "JONN$"

gNameChoice_Kamon::
	.string "KAMON$"

gNameChoice_Karl::
	.string "KARL$"

gNameChoice_Taylor::
	.string "TAYLOR$"

gNameChoice_Oscar::
	.string "OSCAR$"

gNameChoice_Hiro::
	.string "HIRO$"

gNameChoice_Max::
	.string "MAX$"

gNameChoice_Jon::
	.string "JON$"

gNameChoice_Ralph::
	.string "RALPH$"

gNameChoice_Kay::
	.string "KAY$"

gNameChoice_Tosh::
	.string "TOSH$"

gNameChoice_Roak::
	.string "ROAK$"

gNameChoice_Omi::
	.string "OMI$"

gNameChoice_Jodi::
	.string "JODI$"

gNameChoice_Amanda::
	.string "AMANDA$"

gNameChoice_Hillary::
	.string "HILLARY$"

gNameChoice_Makey::
	.string "MAKEY$"

gNameChoice_Michi::
	.string "MICHI$"

gNameChoice_Paula::
	.string "PAULA$"

gNameChoice_June::
	.string "JUNE$"

gNameChoice_Cassie::
	.string "CASSIE$"

gNameChoice_Rey::
	.string "REY$"

gNameChoice_Seda::
	.string "SEDA$"

gNameChoice_Kiko::
	.string "KIKO$"

gNameChoice_Mina::
	.string "MINA$"

gNameChoice_Norie::
	.string "NORIE$"

gNameChoice_Sai::
	.string "SAI$"

gNameChoice_Momo::
	.string "MOMO$"

gNameChoice_Suzi::
	.string "SUZI$"

gControlsGuide_Text_Intro::
	.string "The various buttons will be explained in\n"
	.string "the order of their importance.$"

gControlsGuide_Text_DPad::
	.string "Moves the main character.\n"
	.string "Also used to choose various data\n"
	.string "headings.$"

gControlsGuide_Text_AButton::
	.string "Used to confirm a choice, check\n"
	.string "things, chat, and scroll text.$"

gControlsGuide_Text_BButton::
	.string "Used to exit, cancel a choice,\n"
	.string "and cancel a mode.$"

gControlsGuide_Text_StartButton::
	.string "Press this button to open the\n"
	.string "MENU.$"

gControlsGuide_Text_SelectButton::
	.string "Used to shift items and to use\n"
	.string "a registered item.$"

gControlsGuide_Text_LRButtons::
	.string "If you need help playing the\n"
	.string "game, or on how to do things,\n"
	.string "press the L or R Button.$"

gOakSpeech_Text_AskPlayerGender::
	.string "-Selecciona un Genero-$"

gPikachuIntro_Text_Page1::
	.string "Las cosas parecían estar tranquilas\n"
	.string "en la región de Kanto. El campeón, \n"
	.string "Lance, mantuvo a flote a la\n"
	.string "región tras la Gran Guerra,$"

gPikachuIntro_Text_Page2::
	.string "Sin embargo, pronto, apareció una\n"
	.string "gran piedra en el zapato para Kanto: el\n"
	.string "Team Rocket. Una organización criminal\n"
	.string "muy respetada por diversas pandillas.$"

gPikachuIntro_Text_Page3::
	.string "Buscando un mundo dominado por la gran R,\n"
	.string "recorrerían Ciudades, Rutas y Calles\n"
	.string "para reclutar Entrenadores ambiciosos\n"
	.string "para que realicen el Trabajo Sucio.\n"
	.string "\n"
	.string "Nuestra historia seguirá a uno de\n"
	.string "estos Entrenadores.$"

gOakSpeech_Text_WelcomeToTheWorld::
	.string "Hola, bienvenido al\n"
	.string "team rocket.\p"
	.string "Este es el Mundo Pokémon.\p"
	.string "Eres una de las pocas personas\n"
	.string "afortunadas a los que se les ha\l"
	.string "permitido entrar a nuestra\l"
	.string "organizacion.\p"
	.string "¡Más te vale demostrar\n"
	.string "ser digno de ello!\p"
	.string "Si eres como los otros novatos,\n"
	.string "Supongo que nunca tuviste la\l"
	.string "oportunidad de tener un Pokémon\l"
	.string "en tu vida, ¿O me equivoco?\p$"

gOakSpeech_Text_ThisWorld::
	.string "En tal caso, dejame decirte\n"
	.string "que este…$"

gOakSpeech_Text_IsInhabitedFarAndWide::
	.string "…¡Es tu dia de suerte!\p$"

gOakSpeech_Text_IStudyPokemon::
	.string "Cada uno de ustedes recibirá\n"
	.string "una de estas bellezas.\p"
	.string "No quiero escuchar quejas de tu\n"
	.string "parte.\p"
	.string "Si no te gusta, entonces sal\n"
	.string "y robate algo mejor.\p"
	.string "¡Esta es una organizacion criminal,\n"
	.string "no una caridad para llorar\l"
	.string "beneficios en voz alta!\p$"

gOakSpeech_Text_TellMeALittleAboutYourself::
	.string "De todas formas, la charla\n"
	.string "no es importante ahora…\p"
	.string "¿Qué tal si me cuentas un poco\n"
	.string "sobre ti?\p$"

gOakSpeech_Text_YourNameWhatIsIt::
	.string "Supongo que tienes un nombre,\n"
	.string "¿verdad?\p$"

gOakSpeech_Text_SoYourNameIsPlayer::
	.string "¿Es {PLAYER}?$"

gOakSpeech_Text_WhatWasHisName::
	.string "Entonces es {PLAYER}, entiendo.\p$"

gOakSpeech_Text_YourRivalsNameWhatWasIt::
	.string "Your rival's name, what was it now?$"

gOakSpeech_Text_ConfirmRivalName::
	.string "…Er, was it {RIVAL}?$"

gOakSpeech_Text_RememberRivalsName::
	.string "That's right! I remember now!\n"
	.string "His name is {RIVAL}!\p$"

gOakSpeech_Text_LetsGo::
	.string "¡Muy bien, {PLAYER}!\p"
	.string "¡Te espera una nueva vida de\n"
	.string "violencia, robo y demas delitos!\p"
	.string "¡Trata de mantenerte alejado de\n"
	.string "la policía, cumple las órdenes de\l"
	.string "tus superiores y no muestres piedad\l"
	.string "a nadie!\p"
	.string "Haz eso y tal vez algún día puedas\n"
	.string "llegar a ser alguien poderoso como yo.\p"
	.string "O tal vez no, ¿quién sabe?\p"
	.string "¡Ahora muévete, no tenemos todo el\n"
	.string "día!$"
